version: "3.8"

services:

  backend:
    build:
      context: ./backend

    container_name: medstock-backend

    ports:
      - "5000:5000"

    env_file:
      - .env

    depends_on:
      - postgres

    restart: always  # Restart the backend automatically if it crashes

  postgres:
    image: postgres:15

    container_name: medstock-db

    restart: always  # Restart the database automatically if it crashes

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
