---
app_name: medstock-monitor
db_container_name: medstock-db
network_name: medstock-network

github_org: paulrwagasana
image_tag: ci
app_image: "ghcr.io/{{ github_org }}/{{ app_name }}:{{ image_tag }}"

# Azure Terraform deployment.
deploy_local_db: false
db_host: medstock-psql-server-esrzd.postgres.database.azure.com
db_fqdn: "{{ db_host }}"
db_port: 5432
db_name: medstock
db_user: postgres
# Change to the real Azure DB password before running the playbook.
db_password: "ChangeThisPasswordBeforeRunningThePlaybook"
vault_db_password: "{{ db_password }}"

ghcr_package_is_private: false
registry_url: ""
registry_username: ""
registry_password: ""
vault_ghcr_token: ""

container_port: 5000
app_port: 5000

base_packages:
  - ca-certificates
  - curl
  - gnupg
  - docker.io
  - python3-docker
  - ufw
  - fail2ban

allowed_ports:
  - 22
  - "{{ app_port }}"
